### ISSUE TITLE
Dependency with website_sale missing

### ISSUE THREAD

**Issue by mapeal2** [OdooCommunityWidgets/website_multi_image#16]
If this addon is installed without the website_sale addon being installed, installation fails.

I think the issue is in the file **openerp**.py:

'depends': ['product','sale'],

**Comment by lukebranch** [comment]
@mapeal2 ,

Thanks for your issue report. The fix has been merged into the 8.0 branch here:

https://github.com/OdooCommunityWidgets/website_multi_image/commit/434c189c1923f7ab91e3034cd19c5da87582fade

You should just be able to do a git pull in your module directory (if you cloned the repository from github) and then just update the module.
