### ISSUE TITLE
Prices and taxes in shiping cart

### ISSUE THREAD

**Issue by nuelgoz** [OdooCommunityWidgets/website_multi_image#18]
Hello, when you install this module changed settings shiping cart on line 51 the formula is different in the shoping cart for Odoo.

thanks.

**Comment by lukebranch** [comment]
@nuelgoz ,

Could you provide screenshots, or a screencast demonstrating your issue. I'm not sure exactly what you mean.

**Comment by nuelgoz** [comment]
code for shoping cart is different from the version of Odoo

![captura de pantalla de 2015-01-29 11 01 46](https://cloud.githubusercontent.com/assets/9434922/5967847/a75a518a-a811-11e4-8dd3-7f30d7889cdf.png)

in this image is already modified, but the difference is in the broken line.

![multimagen](https://cloud.githubusercontent.com/assets/9434922/5967850/b137d81c-a811-11e4-9370-0e5259efcc8f.png)

not calculated correctly if you have from the accounting/configuration menu) so that your tax has the checkbox "Tax included in price" checked.

thanks.

**Comment by lukebranch** [comment]
@nuelgoz ,

Thanks for the report, however this is not related to the installation of the website_multi_image module.

If you look at the code for the website_multi_image module it does not touch any views in website_sale.cart or website_sale_order.website_order_line.

I think you need to check the difference between updates for the two Odoo instances or databases that you are using and update accordingly.

If you feel this is incorrect please provide me with steps to reproduce the issue on a clean, new install of Odoo 8.0 on Ubuntu 14.04 and I will review them and resolve as soon as possible.

I think you may have installed another module that is causing this issue, or you have differences between updates in your two databases that are causing this issue.

**Comment by nuelgoz** [comment]
sorry, the truth is I've just installed some multi-image modules but may be that this did another module.

Cristian, thanks for your time.

**Comment by lukebranch** [comment]
@nuelgoz ,

no problem. I'd recommend searching through the xml files your recently installed modules for anything that relates to the views I mentioned.
