### ISSUE TITLE
Switching Themes breaks view with Slick sliders

### ISSUE THREAD

**Issue by a0c** [OdooCommunityWidgets/website_multi_image#24]
Since `slick.css` is added via Theme facility, switching to a different Theme (e.g. some black one) breaks any view which uses Slick JS library.

Multi-image should be usable regardless of the Theme selected.

Hence, css must be added to `website.assets_frontend` template directly.

**Comment by lukebranch** [comment]
@a0c ,

Thanks for the issue report.
