### ISSUE TITLE
I can not add to cart anymore after I install this app.

### ISSUE THREAD

**Issue by eversatis** [OdooCommunityWidgets/website_multi_image#9]
I can not add to cart anymore after I install the app. Also the minus and plus to change the cart quantity is not working.

Thanks for the excellent contribute!

**Comment by lukebranch** [comment]
@frankmiao2015 ,

Could you provide some more details about your setup, including OS, browser and browser version, and details about how you setup your instance of Odoo? This will help troubleshoot more effectively.

Once I have some more details about your instance i'll try to reproduce the issue. Thanks!

**Comment by eversatis** [comment]
Thanks for the fast reply. I set it up by the instructions of the theopensourcerer as link bellow:

http://www.theopensourcerer.com/2014/09/how-to-install-openerp-odoo-8-on-ubuntu-server-14-04-lts/

And I did Nginx 80 port proxy. Without the image module, it works fine. Both my testing on Windows8 and windows7 are failed. And they all not working on Chrome, IE as well as Firefox. 

Best regards

Frank

**Comment by lukebranch** [comment]
@frankmiao2015 ,

Thanks for the bug report. This issue was introduced due to a javascript conflict with the bootstrap-magnify library. I've temporarily commented out the related css and javascript in the /views/theme.xml file to resolve the issue.

Please do a sudo git pull from your website_multi_image directory and then upgrade the module in your odoo instance. Please feel free to reopen this issue if you find it has not been resolved for you.

**Comment by eversatis** [comment]
The JS conflict is solved but raised another problem. The uploaded images are all displayed with default one. No matter what image you are upload, it will only show the duplicated default image.

Best regards

发自 Surface

发件人: Luke Branch
发送时间: ‎2014‎年‎12‎月‎29‎日, ‎星期一 ‎23‎:‎34
收件人: OdooCommunityWidgets/website_multi_image
抄送: Frank Miao

@frankmiao2015 ,

Thanks for the bug report. This issue was introduced due to a javascript conflict with the bootstrap-magnify library. I've temporarily commented out the related css and javascript in the /views/theme.xml file to resolve the issue.

Please do a sudo git pull from your website_multi_image directory and then upgrade the module in your odoo instance. Please feel free to reopen this issue if you find it has not been resolved for you.
